# Dependencies
markdown:         kramdown
kramdown:
   math_engine:   katex
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title: JDV's Blog
email: delvallejacobo@gmail.com
description: CS, Linguistics, BWF, Tetris, etc. 
baseurl: "/jblog" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: clinchergt
github_username: clinchergt

plugins: [jekyll-paginate, jekyll-gist, execjs, therubyracer, kramdown-math-katex]

paginate:         5
personal:
  repo: https://github.com/clinchergt/jblog
  url: https://jjdv.xyz
  cv: https://jjdv.xyz/personal/cv.pdf

